### ISSUE TITLE
CAPACITOR?

### ISSUE THREAD

**Issue by signatureequipovision** [areo/capacitor-codepush#4]
Why do you call CAPACITOR this plugin?

**Comment by vially** [comment]
This was supposed to be a [CodePush](https://docs.microsoft.com/en-us/appcenter/distribution/codepush/) plugin for [Capacitor](https://capacitorjs.com/) but is no longer maintained.

https://github.com/mapiacompany/capacitor-codepush is a maintained fork so it's recommended to use that instead.
