### ISSUE TITLE
Is the project still alive?

### ISSUE THREAD

**Issue by luanlucho** [areo/capacitor-codepush#5]
Hi, I’d like to know if this project is still alive? Our company are really interested in using this plugin in production, however we’ve noticed the poor weekly downloads… We were just wondering if you recommend looking into other options.

**Comment by alexcroox** [comment]
https://github.com/mapiacompany/capacitor-codepush

**Comment by vially** [comment]
Sorry for the late reply. This project is no longer maintained so I would recommend to use https://github.com/mapiacompany/capacitor-codepush instead.
